### ISSUE TITLE
CSS Styles

### ISSUE THREAD

**Issue by hasis** [CHOMPI-Club/CHOMPI-Pal#1]
![Image](https://github.com/user-attachments/assets/24bc4162-e9b0-43eb-8bc2-8ede3fbbac14)
![Image](https://github.com/user-attachments/assets/979bf481-b265-4d6c-86c2-09d902ecc7e5)
![Image](https://github.com/user-attachments/assets/867c36ac-6cff-4bf4-bbf3-122424ba216a)
![Image](https://github.com/user-attachments/assets/f3ac644f-5ad6-4478-8556-182272449f0f)

**Comment by hasis** [comment]
@CHOMPI-Tobias -- There are four mocks; two peach, two dark mode. Is the intent to have all four options, or are the toggle ones showing when a sample has been loaded?

**Comment by CHOMPI-Tobias** [comment]
Yeah, I think Chels was thinking that the slots would turn the purple color once they had a file loaded onto them. Would that be possible to implement? If not, no worries ;)
Also, if you need any of the design elements... she can send them over in whatever file type you might want... just let me know!

**Comment by hasis** [comment]
Thanks for clarifying! I think I can do that/everything else with CSS. Making progress.

**Comment by hasis** [comment]
@CHOMPI-Tobias the original implementation has sample preview on the slot after something's been selected. I can remove that, up to y'all. This is where we are with Peach: 

![Image](https://github.com/user-attachments/assets/5cbd6880-c801-4309-a853-7bd0b2d1d23e)

Importing fonts and SVGs was the hard bit so we're rollin' now.

**Comment by CHOMPI-Tobias** [comment]
Dude... that looks amazing! I like having that playback feature for sure... let's keep it :)

**Comment by hasis** [comment]
![Image](https://github.com/user-attachments/assets/7e290e99-2de6-4a05-9b99-3ba83584b373)

Dark mode!
